name: Publish on Pypi

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3
      - name: 🐍 Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: 🚀 Publish
        uses: onichandame/pip-upload-action@master
        with:
          username: '__token__'
          password: ${{ secrets.PIP_PASSWORD }}