name: Test WorkFlow

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: 🐍 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: 🦾 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: 🧹 Lint with flake8
        run: |
          make check_code_quality
      - name: 🧪 Test
        env: 
          ROBOFLOW_API_KEY: ${{ secrets.ROBOFLOW_API_KEY }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          PROJECT_VERSION: ${{ secrets.PROJECT_VERSION }}
        run: "python -m unittest"